### ISSUE TITLE
Typescript version？

### ISSUE THREAD

**Issue by kmvan** [imcuttle/node-await-event-emitter#1]
Can I create a typescript version and PR?

**Comment by imcuttle** [comment]
@kmvan  it's welcome!  and please make sure tests work fine.

**Comment by kmvan** [comment]
Sure.

**Comment by imcuttle** [comment]
@kmvan use `await-event-emitter@2` which supports ts

**Comment by kmvan** [comment]
Cool. My code is only half written. Thank you.

![image](https://user-images.githubusercontent.com/3839554/97967563-58922600-1df8-11eb-92c3-6bd201e04fce.png)
