### ISSUE TITLE
Export default

### ISSUE THREAD

**Issue by damian-pastorini** [imcuttle/node-await-event-emitter#2]
Hi @imcuttle , I'm using your library and recently updated to the last version, and now I've started to get an issue on AwaitEventEmitter not been a constructor, this example from the README:
```
const AwaitEventEmitter = require('await-event-emitter')
const emitter = new AwaitEventEmitter()
```
Doesn't work anymore (at least on my project).
After some debug in order to make it work I had to add the default:
```
const AwaitEventEmitter = require('await-event-emitter').default
const emitter = new AwaitEventEmitter()
```
I'm not an expert, but I think this is because how the module is been exported:
`exports.default = AwaitEventEmitter;`
Instead of:
`export default AwaitEventEmitter`

As far I understand you moved to TS, so maybe this is related some compile configuration or something like that maybe?
I don't mind changing my code to include the missing `.default` but you should check it and change the README in case this is not an issue.

BTW: Great job with this module! I totally loved it! :)

**Comment by imcuttle** [comment]
Hi @damian-pastorini , Thanks for your using. I believe the es module is mainstream in the future, and I updated `README.md`

In the future, it should be imported like below (even in node.js):
```
import AwaitEventEmitter from 'await-event-emitter'
```
